apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-gccajqtm
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-gccajqtm:ff7c5670f5fa8cf0da8f01123cc08138969f5fd0@sha256:98543713a240aaf731f18f7d79a2a4ef9b32f5baf36394e16c74f6acf7040831
          name: container-image
